"""initial

Revision ID: 7f6456fe1f8e
Revises: 
Create Date: 2025-10-07 16:17:20.723561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6456fe1f8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('RUNNING', 'ENDED', 'ARCHIVED', 'SCHEDULED', 'CANCELLED', name='lotstate'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_id'), 'lot', ['id'], unique=False)
    op.create_table('user',
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('bid',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='bidstate'), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_id'), 'bid', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_id'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_lot_id'), table_name='lot')
    op.drop_table('lot')
    # ### end Alembic commands ###
