version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: olex
      POSTGRES_PASSWORD: olex
      POSTGRES_DB: olex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://olex:olex@db:5432/olex_db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  postgres_data:
