services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${API_PORT}:8000"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ../backend/app:/app

  frontend:
    build:
      context: ..
      dockerfile: docker/angular/Dockerfile
    working_dir: /frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ../frontend/src:/frontend/src
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:8000
volumes:
  postgres_data: