"""empty message

Revision ID: 134d0d5c52b5
Revises: 
Create Date: 2025-09-24 23:01:45.622006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134d0d5c52b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid',
    sa.Column('lot_id', sa.String(length=120), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_id'), 'bid', ['id'], unique=False)
    op.create_table('lot',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('bid_state', sa.Enum('running', 'ended', name='bidstate'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_id'), 'lot', ['id'], unique=False)
    op.create_table('user',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_lot_id'), table_name='lot')
    op.drop_table('lot')
    op.drop_index(op.f('ix_bid_id'), table_name='bid')
    op.drop_table('bid')
    # ### end Alembic commands ###
