"""change user fields in model user and add apiv1 files

Revision ID: 851c54256465
Revises: 3176a848071c
Create Date: 2025-09-24 23:35:27.701389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851c54256465'
down_revision: Union[str, Sequence[str], None] = '3176a848071c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('user', 'password')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
